# Generated by Django 3.2.16 on 2024-07-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_follow_user_following_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_following_unique',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following'),
        ),
    ]
